r2d2:
    ekf_node:
        ros__parameters:
            frequency: 50.0              # How frequently we publish (even if filter has not updated)
            two_d_mode: false            # If enabled, 3D dimensions (z, roll, pitch, and their derivatives) are forced to 0
            transform_timeout: 0.0       # How long to wait for required transforms to be available
            print_diagnostics: true      # Whether to publish diagnostics
            publish_tf: true

            smooth_lagged_data: true
            history_length: 1.0
            predict_to_current_time: true
            dynamic_process_noise_covariance: true

            initial_estimate_covariance: [0.01, 0.01, 10.0, 1e-9, 1e-9, 0.01, 10.0, 10.0, 1e-9, 1e-9, 1e-9, 10.0, 1e-9, 1e-9, 1e-9]
            process_noise_covariance: [0.01, 0.01, 1e-9, 1e-9, 1e-9, 0.01, 0.05, 0.05, 1e-9, 1e-9, 1e-9, 0.1, 1e-9, 1e-9, 0.05]

            map_frame: map                    # The name of your REP-105 map frame (not needed if world_frame == odom_frame)
            odom_frame: r2d2/odom             # The name of your REP-105 odom frame
            base_link_frame: r2d2/base_link   # The name of your REP-105 base_link frame. Will be the child_frame_id in the output.
            world_frame: r2d2/odom            # The world frame that will be the frame_id in the output.

            twist0: velocity                      # Topic type + number (odomN, poseN, twistN, imuN) and name
            twist0_config: [false, false, false,  # x, y, z
                            false, false, false,  # roll, pitch, yaw
                            true,  true,  true,   # x velocity, y velocity, z velocity
                            false, false, false,   # roll velocity, pitch velocity, yaw velocity
                            false, false, false]   # x acceleration, y acceleration, z acceleration

            pose0: depth
            pose0_config: [false, false, true,
                           false, false, false,
                           false, false, false,
                           false, false, false,
                           false, false, false]

            imu0: imu
            imu0_config: [false, false, false,
                          true,  true,  true,
                          false, false, false,
                          true,  true,  true,
                          false, false, false]

